export enum AuthActionTypes {
    LOGIN_REQUEST = 'LOGIN_REQUEST',
    LOGIN_SUCCESS = 'LOGIN_SUCCESS',
    LOGIN_FAILURE = 'LOGIN_FAILURE',
    SET_USER = 'SET_USER',
    SET_TOKEN = 'SET_TOKEN',
    REMOVE_USER = 'REMOVE_USER',
    REMOVE_TOKEN = 'REMOVE_TOKEN'
};

export enum ProductActionTypes {
    GET_PRODUCT_LIST_REQUEST = 'GET_PRODUCT_LIST_REQUEST',
    GET_PRODUCT_LIST_SUCCESS = 'GET_PRODUCT_LIST_SUCCESS',
    GET_PRODUCT_LIST_FAILURE = 'GET_PRODUCT_LIST_FAILURE',
};